In [1]:
import numpy as np
import pandas as pd
'''
数据转换:  rename, map转换, apply
'''

'''
rename:  对索引和列做替换
DataFrame.rename(mapper=None, index=None, columns=None, axis=None, copy=True, inplace=False, level=None)[source]
Alter axes labels.

Function / dict values must be unique (1-to-1). 
Labels not contained in a dict / Series will be left as-is. Extra labels listed don’t throw an error.

mapping = {'AP指数' : 'AP',  'CDS评分' : 'CDS',  '纤维化分级' : 'result', '肝脏硬度KPA' : 'KPA' }
cleandata.rename(columns=mapping, inplace=True)
cleandata.tail()
'''

'''
map: Series.map(arg, na_action=None)[source] 
    Map values of Series using input correspondence (which can be a dict, Series, or function)
    
f = lambda x : occ_mapping.get(x, x)
fec.contbr_occupation = fec.contbr_occupation.map(f)

get_last_letter = lambda x:x[-1]
last_letters = names.name.map(get_last_letter)
很喜欢这样的处理方式  使用lambda表达式 简洁舒服
'''
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami', 'corned beef', 'Bacon', 'pastrami', 'honey ham', 'nova lox'],'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [3]:
meat_to_animal = {
  'bacon': 'pig',
  'pulled pork': 'pig',
  'pastrami': 'cow',
  'corned beef': 'cow',
  'honey ham': 'pig',
  'nova lox': 'salmon'
}
data['animal'] = data['food'].str.lower().map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [4]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object