In [51]:
from sympy import *
import numpy as np
import pandas as pd
data = pd.read_excel('RS_R.xls')
cleandata = data.iloc[:, [33,35]].dropna()
cleandata.tail()

      A111     A22
28 -0.4337 -2.3450
29 -0.5305 -2.4989
30 -0.4337 -2.3450
31 -0.1433 -1.8833
32 -0.7241 -2.8067

In [54]:
def unsolve(y):
    R = symbols('R')
    return solve(Eq(log(R)/(1-R), y),R)
cleandata['R1'] = cleandata['A111'].map(unsolve)
cleandata['R2'] = cleandata['A22'].map(unsolve)
cleandata

      A111     A22                    R1                     R2
0  -0.2401 -2.0372    [10.9791775442915]    [0.193332737131951]
1  -0.7241 -2.8067    [1.84836701024728]   [0.0744393032096148]
2  -0.7241 -2.8067    [1.84836701024728]   [0.0744393032096148]
3  -0.3369 -2.1911    [6.60231727357433]    [0.158061411458827]
4  -1.5953 -4.1918   [0.360558530431517]   [0.0161800467144701]
5  -0.8209 -2.9606    [1.46598705374541]   [0.0622724485915980]
6  -1.4017 -3.8840   [0.487644373429023]   [0.0224416509887656]
7  -0.7241 -2.8067    [1.84836701024728]   [0.0744393032096148]
8   0.5343 -0.8060                    []     [1.51722267476100]
9  -0.9177 -3.1145    [1.18456932712396]   [0.0522467558596633]
10 -1.0145 -3.2684   [0.971551331658103]   [0.0439473741813202]
11 -0.5305 -2.4989    [3.18181005669936]    [0.107499438728049]
12 -0.5305 -2.4989    [3.18181005669936]    [0.107499438728049]
13 -0.6273 -2.6528    [2.38686679950771]   [0.0892823122223641]
14 -0.5305 -2.4989    [3.18181005669936]    [0.107499438728049]
15 -0.6273 -2.6528    [2.38686679950771]   [0.0892823122223641]
16  1.5023  0.7330                    []                     []
17  0.6311 -0.6521                    []     [2.22960018265029]
18  1.7927  1.1947                    []                     []
19 -2.7569 -6.0386  [0.0789195103817797]  [0.00242000282627190]
20 -0.1433 -1.8833    [22.8283563280204]    [0.238176969047779]
21 -0.9177 -3.1145    [1.18456932712396]   [0.0522467558596633]
22 -0.7241 -2.8067    [1.84836701024728]   [0.0744393032096148]
23 -0.4337 -2.3450    [4.43388620293650]    [0.130013246613395]
24 -0.3369 -2.1911    [6.60231727357433]    [0.158061411458827]
25 -0.7241 -2.8067    [1.84836701024728]   [0.0744393032096148]
26 -0.7241 -2.8067    [1.84836701024728]   [0.0744393032096148]
27 -0.6273 -2.6528    [2.38686679950771]   [0.0892823122223641]
28 -0.4337 -2.3450    [4.43388620293650]    [0.130013246613395]
29 -0.5305 -2.4989    [3.18181005669936]    [0.107499438728049]
30 -0.4337 -2.3450    [4.43388620293650]    [0.130013246613395]
31 -0.1433 -1.8833    [22.8283563280204]    [0.238176969047779]
32 -0.7241 -2.8067    [1.84836701024728]   [0.0744393032096148]